# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/evanj/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14672-DESKTOP-QR17O1B/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.cache/wt [current_project]
set_property parent.project_path C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/ADD.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/COMP.v
  {C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/Circuit 3.v}
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/Circuit2.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/Circuit4.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/MUL.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/MUX2x1.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/REG.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/SHL.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/SHR.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/SUB.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/circuit1.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/TopTestTiming.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/DIV.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/DEC.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/INC.v
  C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/sources_1/new/MOD.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/constraints_1/new/CircuitConstraints.xdc
set_property used_in_implementation false [get_files C:/Users/evanj/OneDrive/SchoolWork/4Senior/574/Assignment1/ECE574Project1/ECE574AProject1.srcs/constraints_1/new/CircuitConstraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Circuit2 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Circuit2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Circuit2_utilization_synth.rpt -pb Circuit2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
